# Generated by Django 3.2.8 on 2022-04-26 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bpmn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bpmn.activity')),
                ('storid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('bpmn.activity', models.Model),
        ),
        migrations.CreateModel(
            name='ActivityGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storid', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storid', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AgentSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storid', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AgentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storid', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storid', models.IntegerField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kipco.activity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storid', models.IntegerField(blank=True, null=True)),
                ('data', models.TextField(max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Intention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storid', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('goals', models.ManyToManyField(blank=True, to='kipco.ActivityGoal')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storid', models.IntegerField(blank=True, null=True)),
                ('data', models.TextField(max_length=1000)),
                ('objects', models.ManyToManyField(blank=True, to='kipco.DataObject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storid', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Desire',
            fields=[
                ('intention_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='kipco.intention')),
            ],
            options={
                'abstract': False,
            },
            bases=('kipco.intention',),
        ),
        migrations.CreateModel(
            name='Socialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storid', models.IntegerField(blank=True, null=True)),
                ('communications', models.ManyToManyField(blank=True, to='kipco.Message')),
                ('perceptions', models.ManyToManyField(blank=True, to='kipco.Agent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MessageFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storid', models.IntegerField(blank=True, null=True)),
                ('association', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kipco.association')),
                ('messages', models.ManyToManyField(blank=True, to='kipco.Message')),
                ('socializations', models.ManyToManyField(blank=True, to='kipco.Socialization')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg_outgoing', to='kipco.activity')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='msg_incoming', to='kipco.activity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IntensiveProcess',
            fields=[
                ('flowelementscontainer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bpmn.flowelementscontainer')),
                ('storid', models.IntegerField(blank=True, null=True)),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kipco.processgoal')),
            ],
            options={
                'abstract': False,
            },
            bases=('bpmn.flowelementscontainer', models.Model),
        ),
        migrations.AddField(
            model_name='association',
            name='data_objects',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kipco.dataobject'),
        ),
        migrations.AddField(
            model_name='agent',
            name='specialties',
            field=models.ManyToManyField(blank=True, to='kipco.AgentSpecialty'),
        ),
        migrations.AddField(
            model_name='agent',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kipco.agenttype'),
        ),
        migrations.AddField(
            model_name='activity',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kipco.agent'),
        ),
        migrations.AddField(
            model_name='activity',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kipco.activitygoal'),
        ),
        migrations.AddField(
            model_name='agent',
            name='desires',
            field=models.ManyToManyField(blank=True, to='kipco.Desire'),
        ),
    ]
