# Generated by Django 3.2.8 on 2022-04-27 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kipco', '0002_rename_perceptions_socialization_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialization',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='socialization',
            name='name',
            field=models.CharField(default='Default', max_length=100),
            preserve_default=False,
        ),
    ]
