# Generated by Django 3.2.8 on 2022-04-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kipco', '0006_auto_20211025_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentspecialty',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agenttype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
