# Generated by Django 3.2.8 on 2022-04-12 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kipco', '0008_auto_20220412_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='storid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitygoal',
            name='storid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='storid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='desire',
            name='storid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='intention',
            name='storid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activitygoal',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kipco.activity'),
        ),
        migrations.AlterField(
            model_name='activitygoal',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kipco.agenttype'),
        ),
        migrations.AlterField(
            model_name='desire',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='desire',
            name='intention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kipco.intention'),
        ),
        migrations.AlterField(
            model_name='intention',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kipco.activity'),
        ),
        migrations.AlterField(
            model_name='intention',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
