# Generated by Django 3.2.8 on 2022-04-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kipco', '0009_auto_20220412_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='desires',
            field=models.ManyToManyField(blank=True, to='kipco.Desire'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='specialties',
            field=models.ManyToManyField(blank=True, to='kipco.AgentSpecialty'),
        ),
    ]
