# Generated by Django 3.2.8 on 2022-04-22 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kipco', '0010_auto_20220421_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storid', models.IntegerField(blank=True, null=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kipco.activity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storid', models.IntegerField(blank=True, null=True)),
                ('data', models.TextField(max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storid', models.IntegerField(blank=True, null=True)),
                ('data', models.TextField(max_length=1000)),
                ('data_object', models.ManyToManyField(blank=True, to='kipco.DataObject')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='intensiveprocess',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kipco.processgoal'),
        ),
        migrations.CreateModel(
            name='Socialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storid', models.IntegerField(blank=True, null=True)),
                ('communications', models.ManyToManyField(blank=True, to='kipco.Message')),
                ('perceptions', models.ManyToManyField(blank=True, to='kipco.Agent')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MessageFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storid', models.IntegerField(blank=True, null=True)),
                ('association', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kipco.association')),
                ('messages', models.ManyToManyField(blank=True, to='kipco.Message')),
                ('socializations', models.ManyToManyField(blank=True, to='kipco.Socialization')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg_outgoing', to='kipco.activity')),
                ('target', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='msg_incoming', to='kipco.activity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='association',
            name='data_objects',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kipco.dataobject'),
        ),
    ]
