# Generated by Django 3.2.8 on 2022-04-22 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kipco', '0011_auto_20220422_0457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitygoal',
            name='activity',
        ),
        migrations.AddField(
            model_name='activity',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kipco.activitygoal'),
        ),
    ]
