# Generated by Django 3.2.8 on 2022-04-21 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bpmn', '0005_remove_flowelementscontainer_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowelementscontainer',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
